apiVersion: skydive.example.com/v1
kind: SkydiveFlowExporter
metadata:
  name: skydiveflowexporter-dev-sample
spec:
  namespace: skydive
  deployment:
    env:
      - name: SKYDIVE_LOGGING_LEVEL
        value: ${SKYDIVE_LOGGING_LEVEL}
      - name: SKYDIVE_PIPELINE_SUBSCRIBER_URL
        value: ws://$(SKYDIVE_ANALYZER_SERVICE_HOST):$(SKYDIVE_ANALYZER_SERVICE_PORT_API)/ws/subscriber/flow
  deployDevEnv: true