// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsDaemonSetSpec) DeepCopyInto(out *AgentsDaemonSetSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsDaemonSetSpec.
func (in *AgentsDaemonSetSpec) DeepCopy() *AgentsDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(AgentsDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentsSpec) DeepCopyInto(out *AgentsSpec) {
	*out = *in
	in.DaemonSet.DeepCopyInto(&out.DaemonSet)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentsSpec.
func (in *AgentsSpec) DeepCopy() *AgentsSpec {
	if in == nil {
		return nil
	}
	out := new(AgentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerDeploymentSpec) DeepCopyInto(out *AnalyzerDeploymentSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerDeploymentSpec.
func (in *AnalyzerDeploymentSpec) DeepCopy() *AnalyzerDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyzerDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerSpec) DeepCopyInto(out *AnalyzerSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerSpec.
func (in *AnalyzerSpec) DeepCopy() *AnalyzerSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyzerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnableSpec) DeepCopyInto(out *EnableSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnableSpec.
func (in *EnableSpec) DeepCopy() *EnableSpec {
	if in == nil {
		return nil
	}
	out := new(EnableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowExporterDeploymentSpec) DeepCopyInto(out *FlowExporterDeploymentSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowExporterDeploymentSpec.
func (in *FlowExporterDeploymentSpec) DeepCopy() *FlowExporterDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(FlowExporterDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowExporterSpec) DeepCopyInto(out *FlowExporterSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowExporterSpec.
func (in *FlowExporterSpec) DeepCopy() *FlowExporterSpec {
	if in == nil {
		return nil
	}
	out := new(FlowExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConnectorDeploymentSpec) DeepCopyInto(out *PrometheusConnectorDeploymentSpec) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConnectorDeploymentSpec.
func (in *PrometheusConnectorDeploymentSpec) DeepCopy() *PrometheusConnectorDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusConnectorDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConnectorSpec) DeepCopyInto(out *PrometheusConnectorSpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConnectorSpec.
func (in *PrometheusConnectorSpec) DeepCopy() *PrometheusConnectorSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusConnectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Skydive) DeepCopyInto(out *Skydive) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Skydive.
func (in *Skydive) DeepCopy() *Skydive {
	if in == nil {
		return nil
	}
	out := new(Skydive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Skydive) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkydiveList) DeepCopyInto(out *SkydiveList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Skydive, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkydiveList.
func (in *SkydiveList) DeepCopy() *SkydiveList {
	if in == nil {
		return nil
	}
	out := new(SkydiveList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SkydiveList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkydiveSpec) DeepCopyInto(out *SkydiveSpec) {
	*out = *in
	out.Enable = in.Enable
	in.Agents.DeepCopyInto(&out.Agents)
	in.Analyzer.DeepCopyInto(&out.Analyzer)
	in.FlowExporter.DeepCopyInto(&out.FlowExporter)
	in.PrometheusConnector.DeepCopyInto(&out.PrometheusConnector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkydiveSpec.
func (in *SkydiveSpec) DeepCopy() *SkydiveSpec {
	if in == nil {
		return nil
	}
	out := new(SkydiveSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkydiveStatus) DeepCopyInto(out *SkydiveStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkydiveStatus.
func (in *SkydiveStatus) DeepCopy() *SkydiveStatus {
	if in == nil {
		return nil
	}
	out := new(SkydiveStatus)
	in.DeepCopyInto(out)
	return out
}
