# permissions for end users to edit prometheusconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusconnector-editor-role
rules:
- apiGroups:
  - skydive.example.com
  resources:
  - prometheusconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skydive.example.com
  resources:
  - prometheusconnectors/status
  verbs:
  - get
