# permissions for end users to view prometheusconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheusconnector-viewer-role
rules:
- apiGroups:
  - skydive.example.com
  resources:
  - prometheusconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skydive.example.com
  resources:
  - prometheusconnectors/status
  verbs:
  - get
