# permissions for end users to edit skydiveflowexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skydiveflowexporter-editor-role
rules:
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveflowexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveflowexporters/status
  verbs:
  - get
