# permissions for end users to view skydiveflowexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skydiveflowexporter-viewer-role
rules:
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveflowexporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - skydive.example.com
  resources:
  - skydiveflowexporters/status
  verbs:
  - get
