apiVersion: v1
kind: Route
metadata:
  labels:
    app: skydive-prometheus-connector
  name: skydive-prometheus-connector
spec:
  port:
    targetPort: api
  to:
    kind: Service
    name: skydive-prometheus-connector
    weight: 100
  wildcardPolicy: None